source 'https://rubygems.org'

gem 'shotgun'
gem 'activerecord', '4.2.5', :require => 'active_record'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3', '~>1.3.6'
gem 'pry'
gem 'require_all'